### PR TITLE
Added some more functionality.

### PR DESCRIPTION
**Pull request by Bravo-ZR**
…ontinue to function if the user wants to.

### CODE REVIEW

**Comment by AkhilProto** [comment]
Hey! Thank you for contributing to my mini project! I do have a small change in your code. The calculate_logarithm and calculate_exponentation arent working i.e they arent defined in the code. I have never got a pull request on my repos so i dont know how to propose these changes in the platform. So here's the updated code and edit these in your branch/repo and I will merge them! I know I am a bit dumb in this thing. but if you know how to do it, please tell me, that would be helpful!


https://pastebin.com/dRCdhc5a

**Comment by Bravo-ZR** [comment]
> Hey! Thank you for contributing to my mini project! I do have a small change in your code. The calculate_logarithm and calculate_exponentation arent working i.e they arent defined in the code. I have never got a pull request on my repos so i dont know how to propose these changes in the platform. So here's the updated code and edit these in your branch/repo and I will merge them! I know I am a bit dumb in this thing. but if you know how to do it, please tell me, that would be helpful!
> 
> https://pastebin.com/dRCdhc5a

Hello, Thanks for replying. I changed the code as you wanted.

**Comment by Bravo-ZR** [comment]
> > Hey! Thank you for contributing to my mini project! I do have a small change in your code. The calculate_logarithm and calculate_exponentation arent working i.e they arent defined in the code. I have never got a pull request on my repos so i dont know how to propose these changes in the platform. So here's the updated code and edit these in your branch/repo and I will merge them! I know I am a bit dumb in this thing. but if you know how to do it, please tell me, that would be helpful!
> > https://pastebin.com/dRCdhc5a
> 
> Hello, Thanks for replying. I changed the code as you wanted.

Also I am not sure how to add the log and expo to your code since I don't have much knowledge about the math module.

**Comment by AkhilProto** [comment]
> > > Hey! Thank you for contributing to my mini project! I do have a small change in your code. The calculate_logarithm and calculate_exponentation arent working i.e they arent defined in the code. I have never got a pull request on my repos so i dont know how to propose these changes in the platform. So here's the updated code and edit these in your branch/repo and I will merge them! I know I am a bit dumb in this thing. but if you know how to do it, please tell me, that would be helpful!
> > > https://pastebin.com/dRCdhc5a
> > 
> > 
> > Hello, Thanks for replying. I changed the code as you wanted.
> 
> Also I am not sure how to add the log and expo to your code since I don't have much knowledge about the math module.

No problem! I have added it in the code.

**Pull request merged**
